In [15]:
import numpy as np

arr = np.array([1,2,3,4])

arr


array([1, 2, 3, 4])

In [17]:
a = np.insert(arr, 1, 10)
a

array([ 1, 10,  2,  3,  4])

In [25]:
b = np.array([[1,2],[3,4]])
print(b.ndim)
print(b.sum(axis=0))
print(b.sum(axis=1))

2
[4 6]
[3 7]


In [26]:
np.insert(b, 1, 5, axis=1)

array([[1, 5, 2],
       [3, 5, 4]])

In [27]:
np.insert(b, 0, 5, axis=0)

array([[5, 5],
       [1, 2],
       [3, 4]])