In [5]:
import numpy as np

valores = np.genfromtxt("dados2.csv", delimiter=";", skip_header=1)
print(valores)

[[10. 20. 30.]
 [40. 50. 60.]
 [70. 80. 90.]]


In [9]:
print(valores[:2])

[[10. 20. 30.]
 [40. 50. 60.]]
