In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

a


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
test = np.array_split(a, 2)
print(test[0][0][1])

2


In [6]:
for array in test:
    print(array)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
