In [2]:
import numpy as np

a = np.array([1,2,3])

np.append(a, [4,5,6])

array([1, 2, 3])

In [11]:
a = np.array([[1,2], [3,4]])
np.append(a, [[5,6]])

array([1, 2, 3, 4, 5, 6])

In [12]:
np.append(a, [[5,6]], axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])